# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "[$directory$git_branch]($style)$character"

# Inserts a blank line between shell prompts
add_newline = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character]
error_symbol = "[âœ—](bold red)"
success_symbol = "[â¯](bold #A5D6A7)[â¯](bold #FFF59D)[â¯](bold #FFAB91)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = 'ğŸ…° '

[aws.region_aliases]
us-east-1 = 'us'
eu-central-1 = 'eu'

[git_branch]
truncation_length = 20
truncation_symbol = ''

[nodejs]
format = 'via [ğŸ¤– $version](bold green) '